import { useEffect } from "react";
import { useLocalization } from "cs2/l10n";
import { ModuleRegistryExtend } from "cs2/modding";
import { bindValue, trigger, useValue } from "cs2/api";
import { VanillaComponentResolver } from "../VanillaComponentResolver/VanillaComponentResolver";
import mod from "../../../mod.json";
import { tool } from "cs2/bindings";
import locale from "../lang/en-US.json";
import { getModule } from "cs2/modding";
import { Tooltip } from "cs2/ui";
import marqueeToolSrc from "../../img/icon_Marquee_Off.svg";
import marqueeToolActiveSrc from "../../img/icon_Marquee_Active.svg";

import styles from "./LayeredSelectionDisplaySections.module.scss";

// These establishes the binding with C# side. Without C# side game ui will crash.
const raycastTarget$ = bindValue<number>(mod.id, "RaycastTarget");
const isGame$ = bindValue<boolean>(mod.id, "IsGame");
const selectedVanillaFilters$ = bindValue<VanillaFilters>(
    mod.id,
    "SelectedVanillaFilters"
);
const isMarqueeToolSelected$ = bindValue<boolean>(
    mod.id,
    "IsMarqueeToolSelected"
);
const isFiltersPanelVisible$ = bindValue<boolean>(
    mod.id,
    "IsFiltersPanelVisible"
);

// These contain the coui paths to Unified Icon Library svg assets
const uilStandard = "coui://uil/Standard/";

const allSrc = uilStandard + "StarAll.svg";
const networkSrc = uilStandard + "Network.svg";
const decalsSrc = uilStandard + "Decals.svg";
const treeSrc = uilStandard + "TreeAdult.svg";
const plantSrc = uilStandard + "FlowerPot.svg";
const buildingSrc = uilStandard + "House.svg";
const propsSrc = uilStandard + "BenchAndLampProps.svg";

// Saving strings for events and translations.
const tooltipDescriptionPrefix =
    "LAYERED_SELECTION_DISPLAY_DESCRIPTION.";
const sectionTitlePrefix =
    "LAYERED_SELECTION_DISPLAY.";
const toolsSectionTitle =
    "LAYERED_SELECTION_DISPLAY_MAINPANEL.Tools";
const marqueeToolTooltip =
    "LAYERED_SELECTION_DISPLAY_MAINPANEL.MarqueeToolToolTip";

// This functions trigger an event on C# side and C# designates the method to implement.
function handleClick(eventName: string) {
    trigger(mod.id, eventName);
}

function onChangeFiltersPanelVisibility() {
    trigger(mod.id, "OnChangeFiltersPanelVisibility");
}

// This functions trigger an event on C# side and C# designates the method to implement.
function changeSelectedVanillaFilter(filter: VanillaFilters) {
    trigger(mod.id, "ChangeVanillaFilter", filter);
}

function onChangeListPanelVisibility() {
    trigger(mod.id, "OnChangeListPanelVisibility");
}

enum VanillaFilters {
    None = 0,
    Networks = 1,
    Buildings = 2,
    Trees = 4,
    Plants = 8,
    Decals = 16,
    Props = 32,
    Surfaces = 64,
    All = 128,
}

const descriptionToolTipStyle = getModule(
    "game-ui/common/tooltip/description-tooltip/description-tooltip.module.scss",
    "classes"
);

// This is working, but it's possible a better solution is possible.
function descriptionTooltip(
    tooltipTitle: string | null,
    tooltipDescription: string | null
): JSX.Element {
    return (
        <>
            <div className={descriptionToolTipStyle.title}>
                {tooltipTitle}
            </div>

            <div className={descriptionToolTipStyle.content}>
                {tooltipDescription}
            </div>
        </>
    );
}

export const LayeredSelectionDisplaySectionsComponent: ModuleRegistryExtend =
    (Component: any) => {
        return (props) => {

            const { children, ...otherProps } = props || {};

            // These get the value of the bindings.
            const defaultToolActive =
                useValue(tool.activeTool$).id == tool.DEFAULT_TOOL;

            const selectedVanillaFilters =
                useValue(selectedVanillaFilters$);

            const isGame =
                useValue(isGame$);

            const raycastTarget =
                useValue(raycastTarget$);

            const isMarqueeToolSelected =
                useValue(isMarqueeToolSelected$);

            const marqueeToolIcon =
                isMarqueeToolSelected
                    ? marqueeToolActiveSrc
                    : marqueeToolSrc;

            // This is now the flag that controls whether
            // our filters panel is expanded or minimized.
            const isFiltersPanelVisible =
                useValue(isFiltersPanelVisible$);

            /*
             * ---------------------------------------------------------
             * MINIMIZED VANILLA WRAPPER
             * ---------------------------------------------------------
             *
             * Component() creates the vanilla MouseToolOptions tree.
             *
             * We do NOT replace it.
             * We only modify the wrapper generated by the game.
             */
            useEffect(() => {

                if (!defaultToolActive || !isGame) {
                    return;
                }

                const wrapper = document.querySelector(
                    ".wrapper_eKY"
                ) as HTMLElement | null;

                if (!wrapper) {
                    return;
                }

                if (!isFiltersPanelVisible) {

                    // Minimized dimensions.
                    wrapper.style.setProperty(
                        "width",
                        "70rem",
                        "important"
                    );

                    wrapper.style.setProperty(
                        "height",
                        "10rem",
                        "important"
                    );

                    wrapper.style.setProperty(
                        "min-width",
                        "70rem",
                        "important"
                    );

                    wrapper.style.setProperty(
                        "min-height",
                        "10rem",
                        "important"
                    );

                    // The complete minimized wrapper is clickable.
                    wrapper.style.setProperty(
                        "cursor",
                        "pointer",
                        "important"
                    );

                    wrapper.onclick = () => {
                        onChangeFiltersPanelVisibility();
                    };

                } else {

                    // Return control to the vanilla component.
                    wrapper.style.removeProperty("width");
                    wrapper.style.removeProperty("height");
                    wrapper.style.removeProperty("min-width");
                    wrapper.style.removeProperty("min-height");
                    wrapper.style.removeProperty("cursor");

                    wrapper.onclick = null;
                }

                return () => {
                    if (wrapper) {
                        wrapper.onclick = null;
                    }
                };

            }, [
                isFiltersPanelVisible,
                defaultToolActive,
                isGame
            ]);

            // Saving strings for events and translations.
            const surfacesID = "SurfacesFilterButton";

            // Translation handling.
            const { translate } = useLocalization();

            const filterSectionTitle =
                translate(
                    sectionTitlePrefix + "Filter",
                    locale["LAYERED_SELECTION_DISPLAY.Filter"]
                );

            const surfacesFilterTooltip =
                translate(
                    tooltipDescriptionPrefix + surfacesID,
                    locale[
                        "LAYERED_SELECTION_DISPLAY_DESCRIPTION.SurfacesFilterButton"
                    ]
                );

            const toolModeTitle =
                translate(
                    "Toolbar.TOOL_MODE_TITLE",
                    "Tool Mode"
                );

            const surfacesSrc =
                uilStandard + "ShovelSurface.svg";

            const surfacesFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[SurfacesFilterButton]"
                );

            const allFiltersTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[AllFilters]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[AllFilters]"
                    ]
                );

            const allFiltersDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[AllFilters]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[AllFilters]"
                    ]
                );

            const vanillaNetworksFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[VanillaNetworksFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[VanillaNetworksFilter]"
                    ]
                );

            const vanillaNetworksFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[VanillaNetworksFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[VanillaNetworksFilter]"
                    ]
                );

            const buildingFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[BuildingFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[BuildingFilter]"
                    ]
                );

            const buildingFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[BuildingFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[BuildingFilter]"
                    ]
                );

            const treeFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[TreeFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[TreeFilter]"
                    ]
                );

            const treeFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[TreeFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[TreeFilter]"
                    ]
                );

            const plantFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[PlantFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[PlantFilter]"
                    ]
                );

            const plantFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[PlantFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[PlantFilter]"
                    ]
                );

            const decalFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[DecalFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[DecalFilter]"
                    ]
                );

            const decalFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[DecalFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[DecalFilter]"
                    ]
                );

            const propFilterTitle =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_TITLE[PropFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_TITLE[PropFilter]"
                    ]
                );

            const propFilterDescription =
                translate(
                    "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[PropFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[PropFilter]"
                    ]
                );

            const vanillaSurfaceFilterDescription =
                translate(
                    "LAYERED_SELECTION_DISPLAY.TOOLTIP_DESCRIPTION[VanillaSurfaceFilter]",
                    locale[
                        "LayeredSelectionDisplay.TOOLTIP_DESCRIPTION[VanillaSurfaceFilter]"
                    ]
                );

            const toolsSectionTitleTranslated =
                translate(
                    "LAYERED_SELECTION_DISPLAY_MAINPANEL.Tools",
                    locale[
                        "LAYERED_SELECTION_DISPLAY_MAINPANEL.Tools"
                    ]
                );

            const marqueeToolTooltipTranslated =
                translate(
                    "LAYERED_SELECTION_DISPLAY_MAINPANEL.MarqueeToolToolTip",
                    locale[
                        "LAYERED_SELECTION_DISPLAY_MAINPANEL.MarqueeToolToolTip"
                    ]
                );

            /*
             * ---------------------------------------------------------
             * ORIGINAL COMPONENT
             * ---------------------------------------------------------
             *
             * IMPORTANT:
             * This is ALWAYS returned.
             */
            const result: JSX.Element = Component();

            /*
             * ---------------------------------------------------------
             * OPEN STATE
             * ---------------------------------------------------------
             *
             * When the panel is visible, preserve the existing
             * functionality exactly as before.
             */
            if (
                defaultToolActive &&
                isGame &&
                isFiltersPanelVisible
            ) {
                result.props.children?.push(
                    <>
                        {raycastTarget == 0 && (
                            <>
                                <VanillaComponentResolver.instance.Section
                                    title={
                                        toolsSectionTitleTranslated ?? ""
                                    }
                                >
                                    <VanillaComponentResolver.instance.ToolButton
                                        onSelect={() =>
                                            onChangeListPanelVisibility()
                                        }
                                        tooltip={
                                            marqueeToolTooltipTranslated
                                        }
                                        src={marqueeToolIcon}
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        onSelect={() =>
                                            onChangeFiltersPanelVisibility()
                                        }
                                        tooltip="Hide filters panel"
                                        src="coui://uil/Standard/ArrowsMinimizeBold.svg"
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />
                                </VanillaComponentResolver.instance.Section>

                                <VanillaComponentResolver.instance.Section
                                    title={
                                        filterSectionTitle ?? ""
                                    }
                                >
                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.All) ==
                                            VanillaFilters.All
                                        }
                                        tooltip={descriptionTooltip(
                                            allFiltersTitle,
                                            allFiltersDescription
                                        )}
                                        src={allSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.All
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.Buildings) ==
                                            VanillaFilters.Buildings
                                        }
                                        tooltip={descriptionTooltip(
                                            buildingFilterTitle,
                                            buildingFilterDescription
                                        )}
                                        src={buildingSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.Buildings
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.Trees) ==
                                            VanillaFilters.Trees
                                        }
                                        tooltip={descriptionTooltip(
                                            treeFilterTitle,
                                            treeFilterDescription
                                        )}
                                        src={treeSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.Trees
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.Plants) ==
                                            VanillaFilters.Plants
                                        }
                                        tooltip={descriptionTooltip(
                                            plantFilterTitle,
                                            plantFilterDescription
                                        )}
                                        src={plantSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.Plants
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.Decals) ==
                                            VanillaFilters.Decals
                                        }
                                        tooltip={descriptionTooltip(
                                            decalFilterTitle,
                                            decalFilterDescription
                                        )}
                                        src={decalsSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.Decals
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />

                                    <VanillaComponentResolver.instance.ToolButton
                                        selected={
                                            (selectedVanillaFilters &
                                                VanillaFilters.Props) ==
                                            VanillaFilters.Props
                                        }
                                        tooltip={descriptionTooltip(
                                            propFilterTitle,
                                            propFilterDescription
                                        )}
                                        src={propsSrc}
                                        onSelect={() =>
                                            changeSelectedVanillaFilter(
                                                VanillaFilters.Props
                                            )
                                        }
                                        className={
                                            VanillaComponentResolver
                                                .instance
                                                .toolButtonTheme.button
                                        }
                                        focusKey={
                                            VanillaComponentResolver
                                                .instance
                                                .FOCUS_DISABLED
                                        }
                                    />
                                </VanillaComponentResolver.instance.Section>
                            </>
                        )}
                    </>
                );
            }

            /*
             * ---------------------------------------------------------
             * CLOSED STATE
             * ---------------------------------------------------------
             *
             * No panel content is added here.
             *
             * The vanilla MouseToolOptions tree still exists because
             * Component() was called above.
             *
             * The wrapper is reduced by the useEffect.
             */
            if (
                defaultToolActive &&
                isGame &&
                !isFiltersPanelVisible
            ) {
                result.props.children?.push(
                    <>
                        <Tooltip tooltip="Show filters panel">
                            <div
                                className={styles.minimizedPanel}
                            >
                                <span
                                    className={styles.toggleIco}
                                />
                            </div>
                        </Tooltip>
                    </>
                );
            }

            return result;
        };
    };